from app.schemas.practitioner.input import (
    PractitionerCreateSchema,
    PractitionerPatchSchema,
    PractitionerNameCreate,
    PractitionerIdentifierCreate,
    PractitionerTelecomCreate,
    PractitionerAddressCreate,
    PractitionerPhotoCreate,
    PractitionerQualificationCreate,
    PractitionerCommunicationCreate,
)
from app.schemas.practitioner.response import (
    FHIRPractitionerSchema,
    FHIRPractitionerBundle,
    FHIRPractitionerBundleEntry,
    FHIRAttachment,
    FHIRQualification,
    FHIRCommunication,
    PaginatedPractitionerResponse,
    PlainPractitionerResponse,
    PlainPractitionerName,
    PlainPractitionerIdentifier,
    PlainPractitionerTelecom,
    PlainPractitionerAddress,
    PlainPractitionerPhoto,
    PlainQualification,
    PlainPractitionerCommunication,
)

__all__ = [
    # Input
    "PractitionerCreateSchema",
    "PractitionerPatchSchema",
    "PractitionerNameCreate",
    "PractitionerIdentifierCreate",
    "PractitionerTelecomCreate",
    "PractitionerAddressCreate",
    "PractitionerPhotoCreate",
    "PractitionerQualificationCreate",
    "PractitionerCommunicationCreate",
    # Response
    "FHIRPractitionerSchema",
    "FHIRPractitionerBundle",
    "FHIRPractitionerBundleEntry",
    "FHIRAttachment",
    "FHIRQualification",
    "FHIRCommunication",
    "PaginatedPractitionerResponse",
    "PlainPractitionerResponse",
    "PlainPractitionerName",
    "PlainPractitionerIdentifier",
    "PlainPractitionerTelecom",
    "PlainPractitionerAddress",
    "PlainPractitionerPhoto",
    "PlainQualification",
    "PlainPractitionerCommunication",
]
