from app.schemas.common.fhir import (
    FHIRAddress,
    FHIRBundle,
    FHIRBundleEntry,
    FHIRCoding,
    FHIRCodeableConcept,
    FHIRContactPoint,
    FHIRHumanName,
    FHIRIdentifier,
    FHIRPeriod,
    FHIRReference,
    PlainCoding,
    PlainIdentifier,
    PlainIdentifierType,
    PlainReasonCode,
)
from app.schemas.patient.response import (
    FHIRPatientSchema, FHIRPatientBundle, PaginatedPatientResponse,
    PlainPatientResponse, PlainPatientName, PlainPatientTelecom, PlainPatientAddress,
    PlainPatientPhoto, PlainPatientContact, PlainPatientCommunication,
    PlainPatientGeneralPractitioner, PlainPatientLink,
)
from app.schemas.practitioner.response import (
    FHIRPractitionerSchema, FHIRPractitionerBundle, FHIRPractitionerBundleEntry,
    FHIRAttachment, FHIRQualification, FHIRCommunication,
    PaginatedPractitionerResponse, PlainPractitionerResponse,
    PlainPractitionerName, PlainPractitionerIdentifier,
    PlainPractitionerTelecom, PlainPractitionerAddress,
    PlainPractitionerPhoto, PlainQualification, PlainPractitionerCommunication,
)
from app.schemas.encounter.response import (
    FHIREncounterSchema, FHIREncounterBundle, FHIREncounterBundleEntry,
    FHIREncounterStatusHistory, FHIREncounterClassHistory,
    FHIREncounterParticipant, FHIREncounterDiagnosis,
    FHIREncounterHospitalization, FHIREncounterLocation,
    PaginatedEncounterResponse, PlainEncounterResponse,
    PlainEncounterIdentifier, PlainEncounterStatusHistory, PlainEncounterClassHistory,
    PlainEncounterType, PlainEncounterEpisodeOfCare, PlainEncounterBasedOn,
    PlainEncounterParticipantType, PlainEncounterParticipant, PlainEncounterAppointmentRef,
    PlainEncounterReasonCode, PlainEncounterReasonReference, PlainEncounterDiagnosis,
    PlainEncounterAccount, PlainEncounterHospitalization, PlainEncounterLocation,
    PlainEncounterLength,
)
from app.schemas.appointment.response import (
    FHIRAppointmentSchema, FHIRAppointmentBundle, FHIRAppointmentBundleEntry,
    FHIRAppointmentParticipant,
    FHIRRecurrenceTemplate, FHIRRecurrenceWeeklyTemplate, FHIRRecurrenceMonthlyTemplate,
    PaginatedAppointmentResponse, PlainAppointmentResponse,
    PlainAppointmentIdentifier,
    PlainAppointmentServiceCategory, PlainAppointmentServiceType, PlainAppointmentSpecialty,
    PlainAppointmentReasonCode, PlainAppointmentReasonReference,
    PlainAppointmentSupportingInformation, PlainAppointmentSlot, PlainAppointmentBasedOn,
    PlainAppointmentParticipantType, PlainAppointmentParticipant, PlainAppointmentRequestedPeriod,
    PlainWeeklyTemplate, PlainMonthlyTemplate, PlainYearlyTemplate, PlainRecurrenceTemplate,
)
from app.schemas.questionnaire_response.response import (
    FHIRQuestionnaireResponseSchema, FHIRQuestionnaireResponseBundle,
    FHIRQuestionnaireResponseBundleEntry, FHIRQRItem, FHIRAnswer,
    FHIRAnswerCoding, FHIRAnswerQuantity, FHIRAnswerValueReference, FHIRAnswerAttachment,
    PaginatedQuestionnaireResponseResponse, PlainQuestionnaireResponse,
    PlainQRItem, PlainQRAnswer, PlainQRBasedOn, PlainQRPartOf,
    PlainAnswerCoding, PlainAnswerQuantity, PlainAnswerAttachment,
)

__all__ = [
    # Common FHIR
    "FHIRAddress", "FHIRBundle", "FHIRBundleEntry", "FHIRCoding", "FHIRCodeableConcept",
    "FHIRContactPoint", "FHIRHumanName", "FHIRIdentifier", "FHIRPeriod", "FHIRReference",
    "PlainCoding", "PlainIdentifier", "PlainIdentifierType", "PlainReasonCode",
    # Patient
    "FHIRPatientSchema", "FHIRPatientBundle", "PaginatedPatientResponse",
    "PlainPatientResponse", "PlainPatientName", "PlainPatientTelecom", "PlainPatientAddress",
    "PlainPatientPhoto", "PlainPatientContact", "PlainPatientCommunication",
    "PlainPatientGeneralPractitioner", "PlainPatientLink",
    # Practitioner
    "FHIRPractitionerSchema", "FHIRPractitionerBundle", "FHIRPractitionerBundleEntry",
    "FHIRAttachment", "FHIRQualification", "FHIRCommunication",
    "PaginatedPractitionerResponse", "PlainPractitionerResponse",
    "PlainPractitionerName", "PlainPractitionerIdentifier",
    "PlainPractitionerTelecom", "PlainPractitionerAddress",
    "PlainPractitionerPhoto", "PlainQualification", "PlainPractitionerCommunication",
    # Encounter
    "FHIREncounterSchema", "FHIREncounterBundle", "FHIREncounterBundleEntry",
    "FHIREncounterStatusHistory", "FHIREncounterClassHistory",
    "FHIREncounterParticipant", "FHIREncounterDiagnosis",
    "FHIREncounterHospitalization", "FHIREncounterLocation",
    "PaginatedEncounterResponse", "PlainEncounterResponse",
    "PlainEncounterIdentifier", "PlainEncounterStatusHistory", "PlainEncounterClassHistory",
    "PlainEncounterType", "PlainEncounterEpisodeOfCare", "PlainEncounterBasedOn",
    "PlainEncounterParticipantType", "PlainEncounterParticipant", "PlainEncounterAppointmentRef",
    "PlainEncounterReasonCode", "PlainEncounterReasonReference", "PlainEncounterDiagnosis",
    "PlainEncounterAccount", "PlainEncounterHospitalization", "PlainEncounterLocation",
    "PlainEncounterLength",
    # Appointment
    "FHIRAppointmentSchema", "FHIRAppointmentBundle", "FHIRAppointmentBundleEntry",
    "FHIRAppointmentParticipant",
    "FHIRRecurrenceTemplate", "FHIRRecurrenceWeeklyTemplate", "FHIRRecurrenceMonthlyTemplate",
    "PaginatedAppointmentResponse", "PlainAppointmentResponse",
    "PlainAppointmentIdentifier",
    "PlainAppointmentServiceCategory", "PlainAppointmentServiceType", "PlainAppointmentSpecialty",
    "PlainAppointmentReasonCode", "PlainAppointmentReasonReference",
    "PlainAppointmentSupportingInformation", "PlainAppointmentSlot", "PlainAppointmentBasedOn",
    "PlainAppointmentParticipantType", "PlainAppointmentParticipant", "PlainAppointmentRequestedPeriod",
    "PlainWeeklyTemplate", "PlainMonthlyTemplate", "PlainYearlyTemplate", "PlainRecurrenceTemplate",
    # QuestionnaireResponse
    "FHIRQuestionnaireResponseSchema", "FHIRQuestionnaireResponseBundle",
    "FHIRQuestionnaireResponseBundleEntry", "FHIRQRItem", "FHIRAnswer",
    "FHIRAnswerCoding", "FHIRAnswerQuantity", "FHIRAnswerValueReference", "FHIRAnswerAttachment",
    "PaginatedQuestionnaireResponseResponse", "PlainQuestionnaireResponse",
    "PlainQRItem", "PlainQRAnswer", "PlainQRBasedOn", "PlainQRPartOf",
    "PlainAnswerCoding", "PlainAnswerQuantity", "PlainAnswerAttachment",
]
