from app.schemas.common.fhir import (
    FHIRAddress,
    FHIRBundle,
    FHIRBundleEntry,
    FHIRCoding,
    FHIRCodeableConcept,
    FHIRContactPoint,
    FHIRHumanName,
    FHIRIdentifier,
    FHIRPeriod,
    FHIRReference,
    PlainCoding,
    PlainIdentifier,
    PlainIdentifierType,
    PlainReasonCode,
)
from app.schemas.patient.response import (
    FHIRPatientSchema, FHIRPatientBundle, PaginatedPatientResponse,
    PlainPatientResponse, PlainPatientName, PlainPatientTelecom, PlainPatientAddress,
    PlainPatientPhoto, PlainPatientContact, PlainPatientCommunication,
    PlainPatientGeneralPractitioner, PlainPatientLink,
)
from app.schemas.practitioner.response import (
    FHIRPractitionerSchema, FHIRPractitionerBundle, FHIRPractitionerBundleEntry,
    FHIRAttachment, FHIRQualification, FHIRCommunication,
    PaginatedPractitionerResponse, PlainPractitionerResponse,
    PlainPractitionerName, PlainPractitionerIdentifier,
    PlainPractitionerTelecom, PlainPractitionerAddress,
    PlainPractitionerPhoto, PlainQualification, PlainPractitionerCommunication,
)
from app.schemas.encounter.response import (
    FHIREncounterSchema, FHIREncounterBundle, FHIREncounterBundleEntry,
    FHIREncounterStatusHistory, FHIREncounterClassHistory, FHIREncounterBusinessStatus,
    FHIREncounterParticipant, FHIREncounterReason, FHIREncounterDiagnosis,
    FHIREncounterAdmission, FHIREncounterVirtualService, FHIREncounterLocation,
    PaginatedEncounterResponse, PlainEncounterResponse,
    PlainEncounterIdentifier, PlainEncounterStatusHistory, PlainEncounterClassHistory,
    PlainEncounterClass, PlainEncounterBusinessStatus, PlainEncounterServiceType,
    PlainEncounterType, PlainEncounterEpisodeOfCare, PlainEncounterBasedOn,
    PlainEncounterCareTeam, PlainEncounterParticipantType, PlainEncounterParticipant,
    PlainEncounterAppointmentRef, PlainEncounterVirtualService,
    PlainEncounterReason, PlainEncounterReasonUse, PlainEncounterReasonValue,
    PlainEncounterDiagnosis, PlainEncounterDiagnosisCondition, PlainEncounterDiagnosisUse,
    PlainEncounterAccount, PlainEncounterAdmission, PlainEncounterLocation,
    PlainEncounterLength, PlainEncounterCodeableConcept,
)
from app.schemas.appointment.response import (
    FHIRAppointmentSchema, FHIRAppointmentBundle, FHIRAppointmentBundleEntry,
    FHIRAppointmentParticipant,
    FHIRRecurrenceTemplate, FHIRRecurrenceWeeklyTemplate, FHIRRecurrenceMonthlyTemplate,
    PaginatedAppointmentResponse, PlainAppointmentResponse,
    PlainAppointmentIdentifier, PlainAppointmentClass,
    PlainAppointmentServiceCategory, PlainAppointmentServiceType, PlainAppointmentSpecialty,
    PlainAppointmentReason,
    PlainAppointmentSupportingInformation, PlainAppointmentSlot, PlainAppointmentBasedOn,
    PlainAppointmentReplaces, PlainAppointmentVirtualService, PlainAppointmentAccount,
    PlainAppointmentNote, PlainAppointmentPatientInstruction,
    PlainAppointmentParticipantType, PlainAppointmentParticipant, PlainAppointmentRequestedPeriod,
    PlainWeeklyTemplate, PlainMonthlyTemplate, PlainYearlyTemplate, PlainRecurrenceTemplate,
)
from app.schemas.questionnaire_response.response import (
    FHIRQuestionnaireResponseSchema, FHIRQuestionnaireResponseBundle,
    FHIRQuestionnaireResponseBundleEntry, FHIRQRItem, FHIRAnswer,
    FHIRAnswerCoding, FHIRAnswerQuantity, FHIRAnswerValueReference, FHIRAnswerAttachment,
    PaginatedQuestionnaireResponseResponse, PlainQuestionnaireResponse,
    PlainQRItem, PlainQRAnswer, PlainQRBasedOn, PlainQRPartOf,
    PlainAnswerCoding, PlainAnswerQuantity, PlainAnswerAttachment,
)

__all__ = [
    # Common FHIR
    "FHIRAddress", "FHIRBundle", "FHIRBundleEntry", "FHIRCoding", "FHIRCodeableConcept",
    "FHIRContactPoint", "FHIRHumanName", "FHIRIdentifier", "FHIRPeriod", "FHIRReference",
    "PlainCoding", "PlainIdentifier", "PlainIdentifierType", "PlainReasonCode",
    # Patient
    "FHIRPatientSchema", "FHIRPatientBundle", "PaginatedPatientResponse",
    "PlainPatientResponse", "PlainPatientName", "PlainPatientTelecom", "PlainPatientAddress",
    "PlainPatientPhoto", "PlainPatientContact", "PlainPatientCommunication",
    "PlainPatientGeneralPractitioner", "PlainPatientLink",
    # Practitioner
    "FHIRPractitionerSchema", "FHIRPractitionerBundle", "FHIRPractitionerBundleEntry",
    "FHIRAttachment", "FHIRQualification", "FHIRCommunication",
    "PaginatedPractitionerResponse", "PlainPractitionerResponse",
    "PlainPractitionerName", "PlainPractitionerIdentifier",
    "PlainPractitionerTelecom", "PlainPractitionerAddress",
    "PlainPractitionerPhoto", "PlainQualification", "PlainPractitionerCommunication",
    # Encounter
    "FHIREncounterSchema", "FHIREncounterBundle", "FHIREncounterBundleEntry",
    "FHIREncounterStatusHistory", "FHIREncounterClassHistory", "FHIREncounterBusinessStatus",
    "FHIREncounterParticipant", "FHIREncounterReason", "FHIREncounterDiagnosis",
    "FHIREncounterAdmission", "FHIREncounterVirtualService", "FHIREncounterLocation",
    "PaginatedEncounterResponse", "PlainEncounterResponse",
    "PlainEncounterIdentifier", "PlainEncounterStatusHistory", "PlainEncounterClassHistory",
    "PlainEncounterClass", "PlainEncounterBusinessStatus", "PlainEncounterServiceType",
    "PlainEncounterType", "PlainEncounterEpisodeOfCare", "PlainEncounterBasedOn",
    "PlainEncounterCareTeam", "PlainEncounterParticipantType", "PlainEncounterParticipant",
    "PlainEncounterAppointmentRef", "PlainEncounterVirtualService",
    "PlainEncounterReason", "PlainEncounterReasonUse", "PlainEncounterReasonValue",
    "PlainEncounterDiagnosis", "PlainEncounterDiagnosisCondition", "PlainEncounterDiagnosisUse",
    "PlainEncounterAccount", "PlainEncounterAdmission", "PlainEncounterLocation",
    "PlainEncounterLength", "PlainEncounterCodeableConcept",
    # Appointment
    "FHIRAppointmentSchema", "FHIRAppointmentBundle", "FHIRAppointmentBundleEntry",
    "FHIRAppointmentParticipant",
    "FHIRRecurrenceTemplate", "FHIRRecurrenceWeeklyTemplate", "FHIRRecurrenceMonthlyTemplate",
    "PaginatedAppointmentResponse", "PlainAppointmentResponse",
    "PlainAppointmentIdentifier", "PlainAppointmentClass",
    "PlainAppointmentServiceCategory", "PlainAppointmentServiceType", "PlainAppointmentSpecialty",
    "PlainAppointmentReason",
    "PlainAppointmentSupportingInformation", "PlainAppointmentSlot", "PlainAppointmentBasedOn",
    "PlainAppointmentReplaces", "PlainAppointmentVirtualService", "PlainAppointmentAccount",
    "PlainAppointmentNote", "PlainAppointmentPatientInstruction",
    "PlainAppointmentParticipantType", "PlainAppointmentParticipant", "PlainAppointmentRequestedPeriod",
    "PlainWeeklyTemplate", "PlainMonthlyTemplate", "PlainYearlyTemplate", "PlainRecurrenceTemplate",
    # QuestionnaireResponse
    "FHIRQuestionnaireResponseSchema", "FHIRQuestionnaireResponseBundle",
    "FHIRQuestionnaireResponseBundleEntry", "FHIRQRItem", "FHIRAnswer",
    "FHIRAnswerCoding", "FHIRAnswerQuantity", "FHIRAnswerValueReference", "FHIRAnswerAttachment",
    "PaginatedQuestionnaireResponseResponse", "PlainQuestionnaireResponse",
    "PlainQRItem", "PlainQRAnswer", "PlainQRBasedOn", "PlainQRPartOf",
    "PlainAnswerCoding", "PlainAnswerQuantity", "PlainAnswerAttachment",
]
