"""Initial staging schema: staging_medical_record + staging_observation, with clinician review tracking

Revision ID: dee03e2e1437
Revises: 
Create Date: 2026-08-20 15:31:04.125783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee03e2e1437'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE IF NOT EXISTS staging_medical_record_pub_seq START 10000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS staging_observation_pub_seq START 20000 INCREMENT 1')
    op.create_table('staging_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('staging_medical_record_id', sa.BigInteger(), server_default=sa.text("nextval('staging_medical_record_pub_seq')"), nullable=False),
    sa.Column('attachment_content_type', sa.String(), nullable=True),
    sa.Column('attachment_language', sa.String(), nullable=True),
    sa.Column('attachment_data', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('attachment_size', sa.BigInteger(), nullable=True),
    sa.Column('attachment_hash', sa.String(), nullable=True),
    sa.Column('attachment_title', sa.String(), nullable=True),
    sa.Column('attachment_creation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('patient_id', sa.BigInteger(), nullable=True),
    sa.Column('appointment_id', sa.BigInteger(), nullable=True),
    sa.Column('encounter_id', sa.BigInteger(), nullable=True),
    sa.Column('service_request_id', sa.BigInteger(), nullable=True),
    sa.Column('diagnostic_report_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='staging_status'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('review_status', sa.Enum('pending_review', 'accepted', 'rejected', 'needs_revision', name='staging_review_status'), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_record_appointment_id'), 'staging_record', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_staging_record_diagnostic_report_id'), 'staging_record', ['diagnostic_report_id'], unique=False)
    op.create_index(op.f('ix_staging_record_encounter_id'), 'staging_record', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_staging_record_file_id'), 'staging_record', ['file_id'], unique=False)
    op.create_index(op.f('ix_staging_record_id'), 'staging_record', ['id'], unique=False)
    op.create_index(op.f('ix_staging_record_org_id'), 'staging_record', ['org_id'], unique=False)
    op.create_index(op.f('ix_staging_record_patient_id'), 'staging_record', ['patient_id'], unique=False)
    op.create_index(op.f('ix_staging_record_review_status'), 'staging_record', ['review_status'], unique=False)
    op.create_index(op.f('ix_staging_record_service_request_id'), 'staging_record', ['service_request_id'], unique=False)
    op.create_index(op.f('ix_staging_record_staging_medical_record_id'), 'staging_record', ['staging_medical_record_id'], unique=True)
    op.create_index(op.f('ix_staging_record_status'), 'staging_record', ['status'], unique=False)
    op.create_index(op.f('ix_staging_record_user_id'), 'staging_record', ['user_id'], unique=False)
    op.create_table('staging_observation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), server_default=sa.text("nextval('staging_observation_pub_seq')"), nullable=False),
    sa.Column('staging_medical_record_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('registered', 'preliminary', 'final', 'amended', 'corrected', 'cancelled', 'entered_in_error', 'unknown', name='staging_observation_status'), nullable=False),
    sa.Column('code_system', sa.String(), nullable=True),
    sa.Column('code_code', sa.String(), nullable=True),
    sa.Column('code_display', sa.String(), nullable=True),
    sa.Column('code_text', sa.String(), nullable=True),
    sa.Column('subject_type', sa.Enum('Patient', 'Group', 'Device', 'Location', name='obs_subject_ref_type'), nullable=True),
    sa.Column('subject_id', sa.BigInteger(), nullable=True),
    sa.Column('subject_display', sa.String(), nullable=True),
    sa.Column('encounter_type', sa.Enum('Encounter', name='encounter_reference_type'), nullable=True),
    sa.Column('encounter_id', sa.BigInteger(), nullable=True),
    sa.Column('encounter_display', sa.String(), nullable=True),
    sa.Column('effective_date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_instant', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_timing_event', sa.Text(), nullable=True),
    sa.Column('effective_timing_code_system', sa.String(), nullable=True),
    sa.Column('effective_timing_code_code', sa.String(), nullable=True),
    sa.Column('effective_timing_code_display', sa.String(), nullable=True),
    sa.Column('effective_timing_code_text', sa.String(), nullable=True),
    sa.Column('effective_timing_repeat_bounds_duration_value', sa.Numeric(), nullable=True),
    sa.Column('effective_timing_repeat_bounds_duration_comparator', sa.String(), nullable=True),
    sa.Column('effective_timing_repeat_bounds_duration_unit', sa.String(), nullable=True),
    sa.Column('effective_timing_repeat_bounds_duration_system', sa.String(), nullable=True),
    sa.Column('effective_timing_repeat_bounds_duration_code', sa.String(), nullable=True),
    sa.Column('effective_timing_repeat_bounds_range_low_value', sa.Numeric(), nullable=True),
    sa.Column('effective_timing_repeat_bounds_range_low_unit', sa.String(), nullable=True),
    sa.Column('effective_timing_repeat_bounds_range_low_system', sa.String(), nullable=True),
    sa.Column('effective_timing_repeat_bounds_range_low_code', sa.String(), nullable=True),
    sa.Column('effective_timing_repeat_bounds_range_high_value', sa.Numeric(), nullable=True),
    sa.Column('effective_timing_repeat_bounds_range_high_unit', sa.String(), nullable=True),
    sa.Column('effective_timing_repeat_bounds_range_high_system', sa.String(), nullable=True),
    sa.Column('effective_timing_repeat_bounds_range_high_code', sa.String(), nullable=True),
    sa.Column('effective_timing_repeat_bounds_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_timing_repeat_bounds_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_timing_repeat_count', sa.Integer(), nullable=True),
    sa.Column('effective_timing_repeat_count_max', sa.Integer(), nullable=True),
    sa.Column('effective_timing_repeat_duration', sa.Numeric(), nullable=True),
    sa.Column('effective_timing_repeat_duration_max', sa.Numeric(), nullable=True),
    sa.Column('effective_timing_repeat_duration_unit', sa.String(), nullable=True),
    sa.Column('effective_timing_repeat_frequency', sa.Integer(), nullable=True),
    sa.Column('effective_timing_repeat_frequency_max', sa.Integer(), nullable=True),
    sa.Column('effective_timing_repeat_period', sa.Numeric(), nullable=True),
    sa.Column('effective_timing_repeat_period_max', sa.Numeric(), nullable=True),
    sa.Column('effective_timing_repeat_period_unit', sa.String(), nullable=True),
    sa.Column('effective_timing_repeat_day_of_week', sa.Text(), nullable=True),
    sa.Column('effective_timing_repeat_time_of_day', sa.Text(), nullable=True),
    sa.Column('effective_timing_repeat_when', sa.Text(), nullable=True),
    sa.Column('effective_timing_repeat_offset', sa.Integer(), nullable=True),
    sa.Column('issued', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value_quantity_value', sa.Numeric(), nullable=True),
    sa.Column('value_quantity_comparator', sa.String(), nullable=True),
    sa.Column('value_quantity_unit', sa.String(), nullable=True),
    sa.Column('value_quantity_system', sa.String(), nullable=True),
    sa.Column('value_quantity_code', sa.String(), nullable=True),
    sa.Column('value_codeable_concept_system', sa.String(), nullable=True),
    sa.Column('value_codeable_concept_code', sa.String(), nullable=True),
    sa.Column('value_codeable_concept_display', sa.String(), nullable=True),
    sa.Column('value_codeable_concept_text', sa.String(), nullable=True),
    sa.Column('value_string', sa.String(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('value_integer', sa.Integer(), nullable=True),
    sa.Column('value_time', sa.String(), nullable=True),
    sa.Column('value_date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value_range_low_value', sa.Numeric(), nullable=True),
    sa.Column('value_range_low_unit', sa.String(), nullable=True),
    sa.Column('value_range_low_system', sa.String(), nullable=True),
    sa.Column('value_range_low_code', sa.String(), nullable=True),
    sa.Column('value_range_high_value', sa.Numeric(), nullable=True),
    sa.Column('value_range_high_unit', sa.String(), nullable=True),
    sa.Column('value_range_high_system', sa.String(), nullable=True),
    sa.Column('value_range_high_code', sa.String(), nullable=True),
    sa.Column('value_ratio_numerator_value', sa.Numeric(), nullable=True),
    sa.Column('value_ratio_numerator_comparator', sa.String(), nullable=True),
    sa.Column('value_ratio_numerator_unit', sa.String(), nullable=True),
    sa.Column('value_ratio_numerator_system', sa.String(), nullable=True),
    sa.Column('value_ratio_numerator_code', sa.String(), nullable=True),
    sa.Column('value_ratio_denominator_value', sa.Numeric(), nullable=True),
    sa.Column('value_ratio_denominator_comparator', sa.String(), nullable=True),
    sa.Column('value_ratio_denominator_unit', sa.String(), nullable=True),
    sa.Column('value_ratio_denominator_system', sa.String(), nullable=True),
    sa.Column('value_ratio_denominator_code', sa.String(), nullable=True),
    sa.Column('value_sampled_data_origin_value', sa.Numeric(), nullable=True),
    sa.Column('value_sampled_data_origin_unit', sa.String(), nullable=True),
    sa.Column('value_sampled_data_origin_system', sa.String(), nullable=True),
    sa.Column('value_sampled_data_origin_code', sa.String(), nullable=True),
    sa.Column('value_sampled_data_period', sa.Numeric(), nullable=True),
    sa.Column('value_sampled_data_factor', sa.Numeric(), nullable=True),
    sa.Column('value_sampled_data_lower_limit', sa.Numeric(), nullable=True),
    sa.Column('value_sampled_data_upper_limit', sa.Numeric(), nullable=True),
    sa.Column('value_sampled_data_dimensions', sa.Integer(), nullable=True),
    sa.Column('value_sampled_data_data', sa.Text(), nullable=True),
    sa.Column('data_absent_reason_system', sa.String(), nullable=True),
    sa.Column('data_absent_reason_code', sa.String(), nullable=True),
    sa.Column('data_absent_reason_display', sa.String(), nullable=True),
    sa.Column('data_absent_reason_text', sa.String(), nullable=True),
    sa.Column('body_site_system', sa.String(), nullable=True),
    sa.Column('body_site_code', sa.String(), nullable=True),
    sa.Column('body_site_display', sa.String(), nullable=True),
    sa.Column('body_site_text', sa.String(), nullable=True),
    sa.Column('method_system', sa.String(), nullable=True),
    sa.Column('method_code', sa.String(), nullable=True),
    sa.Column('method_display', sa.String(), nullable=True),
    sa.Column('method_text', sa.String(), nullable=True),
    sa.Column('specimen_type', sa.Enum('Specimen', name='obs_specimen_ref_type'), nullable=True),
    sa.Column('specimen_id', sa.BigInteger(), nullable=True),
    sa.Column('specimen_display', sa.String(), nullable=True),
    sa.Column('device_type', sa.Enum('Device', 'DeviceMetric', name='obs_device_ref_type'), nullable=True),
    sa.Column('device_id', sa.BigInteger(), nullable=True),
    sa.Column('device_display', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['staging_medical_record_id'], ['staging_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_encounter_id'), 'staging_observation', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_staging_observation_id'), 'staging_observation', ['id'], unique=False)
    op.create_index(op.f('ix_staging_observation_observation_id'), 'staging_observation', ['observation_id'], unique=True)
    op.create_index(op.f('ix_staging_observation_org_id'), 'staging_observation', ['org_id'], unique=False)
    op.create_index(op.f('ix_staging_observation_staging_medical_record_id'), 'staging_observation', ['staging_medical_record_id'], unique=False)
    op.create_index(op.f('ix_staging_observation_user_id'), 'staging_observation', ['user_id'], unique=False)
    op.create_table('staging_observation_based_on',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_type', sa.Enum('CarePlan', 'DeviceRequest', 'ImmunizationRecommendation', 'MedicationRequest', 'NutritionOrder', 'ServiceRequest', name='obs_based_on_ref_type'), nullable=True),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['staging_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_based_on_observation_id'), 'staging_observation_based_on', ['observation_id'], unique=False)
    op.create_table('staging_observation_category',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['staging_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_category_observation_id'), 'staging_observation_category', ['observation_id'], unique=False)
    op.create_table('staging_observation_component',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('code_system', sa.String(), nullable=True),
    sa.Column('code_code', sa.String(), nullable=True),
    sa.Column('code_display', sa.String(), nullable=True),
    sa.Column('code_text', sa.String(), nullable=True),
    sa.Column('value_quantity_value', sa.Numeric(), nullable=True),
    sa.Column('value_quantity_comparator', sa.String(), nullable=True),
    sa.Column('value_quantity_unit', sa.String(), nullable=True),
    sa.Column('value_quantity_system', sa.String(), nullable=True),
    sa.Column('value_quantity_code', sa.String(), nullable=True),
    sa.Column('value_codeable_concept_system', sa.String(), nullable=True),
    sa.Column('value_codeable_concept_code', sa.String(), nullable=True),
    sa.Column('value_codeable_concept_display', sa.String(), nullable=True),
    sa.Column('value_codeable_concept_text', sa.String(), nullable=True),
    sa.Column('value_string', sa.String(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('value_integer', sa.Integer(), nullable=True),
    sa.Column('value_time', sa.String(), nullable=True),
    sa.Column('value_date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value_range_low_value', sa.Numeric(), nullable=True),
    sa.Column('value_range_low_unit', sa.String(), nullable=True),
    sa.Column('value_range_low_system', sa.String(), nullable=True),
    sa.Column('value_range_low_code', sa.String(), nullable=True),
    sa.Column('value_range_high_value', sa.Numeric(), nullable=True),
    sa.Column('value_range_high_unit', sa.String(), nullable=True),
    sa.Column('value_range_high_system', sa.String(), nullable=True),
    sa.Column('value_range_high_code', sa.String(), nullable=True),
    sa.Column('value_ratio_numerator_value', sa.Numeric(), nullable=True),
    sa.Column('value_ratio_numerator_comparator', sa.String(), nullable=True),
    sa.Column('value_ratio_numerator_unit', sa.String(), nullable=True),
    sa.Column('value_ratio_numerator_system', sa.String(), nullable=True),
    sa.Column('value_ratio_numerator_code', sa.String(), nullable=True),
    sa.Column('value_ratio_denominator_value', sa.Numeric(), nullable=True),
    sa.Column('value_ratio_denominator_comparator', sa.String(), nullable=True),
    sa.Column('value_ratio_denominator_unit', sa.String(), nullable=True),
    sa.Column('value_ratio_denominator_system', sa.String(), nullable=True),
    sa.Column('value_ratio_denominator_code', sa.String(), nullable=True),
    sa.Column('value_sampled_data_origin_value', sa.Numeric(), nullable=True),
    sa.Column('value_sampled_data_origin_unit', sa.String(), nullable=True),
    sa.Column('value_sampled_data_origin_system', sa.String(), nullable=True),
    sa.Column('value_sampled_data_origin_code', sa.String(), nullable=True),
    sa.Column('value_sampled_data_period', sa.Numeric(), nullable=True),
    sa.Column('value_sampled_data_factor', sa.Numeric(), nullable=True),
    sa.Column('value_sampled_data_lower_limit', sa.Numeric(), nullable=True),
    sa.Column('value_sampled_data_upper_limit', sa.Numeric(), nullable=True),
    sa.Column('value_sampled_data_dimensions', sa.Integer(), nullable=True),
    sa.Column('value_sampled_data_data', sa.Text(), nullable=True),
    sa.Column('data_absent_reason_system', sa.String(), nullable=True),
    sa.Column('data_absent_reason_code', sa.String(), nullable=True),
    sa.Column('data_absent_reason_display', sa.String(), nullable=True),
    sa.Column('data_absent_reason_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['staging_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_component_observation_id'), 'staging_observation_component', ['observation_id'], unique=False)
    op.create_table('staging_observation_derived_from',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_type', sa.Enum('DocumentReference', 'ImagingStudy', 'Media', 'QuestionnaireResponse', 'Observation', 'MolecularSequence', name='obs_derived_from_ref_type'), nullable=True),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['staging_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_derived_from_observation_id'), 'staging_observation_derived_from', ['observation_id'], unique=False)
    op.create_table('staging_observation_focus',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['staging_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_focus_observation_id'), 'staging_observation_focus', ['observation_id'], unique=False)
    op.create_table('staging_observation_has_member',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_type', sa.Enum('Observation', 'QuestionnaireResponse', 'MolecularSequence', name='obs_has_member_ref_type'), nullable=True),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['staging_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_has_member_observation_id'), 'staging_observation_has_member', ['observation_id'], unique=False)
    op.create_table('staging_observation_identifier',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('use', sa.String(), nullable=True),
    sa.Column('type_system', sa.String(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_display', sa.String(), nullable=True),
    sa.Column('type_text', sa.String(), nullable=True),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigner', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['staging_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_identifier_observation_id'), 'staging_observation_identifier', ['observation_id'], unique=False)
    op.create_table('staging_observation_interpretation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['staging_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_interpretation_observation_id'), 'staging_observation_interpretation', ['observation_id'], unique=False)
    op.create_table('staging_observation_note',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('author_string', sa.String(), nullable=True),
    sa.Column('author_reference_type', sa.String(), nullable=True),
    sa.Column('author_reference_id', sa.BigInteger(), nullable=True),
    sa.Column('author_reference_display', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['staging_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_note_observation_id'), 'staging_observation_note', ['observation_id'], unique=False)
    op.create_table('staging_observation_part_of',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_type', sa.Enum('MedicationAdministration', 'MedicationDispense', 'MedicationStatement', 'Procedure', 'Immunization', 'ImagingStudy', name='obs_part_of_ref_type'), nullable=True),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['staging_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_part_of_observation_id'), 'staging_observation_part_of', ['observation_id'], unique=False)
    op.create_table('staging_observation_performer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_type', sa.Enum('Practitioner', 'PractitionerRole', 'Organization', 'CareTeam', 'Patient', 'RelatedPerson', name='obs_performer_ref_type'), nullable=True),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['staging_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_performer_observation_id'), 'staging_observation_performer', ['observation_id'], unique=False)
    op.create_table('staging_observation_reference_range',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('low_value', sa.Numeric(), nullable=True),
    sa.Column('low_unit', sa.String(), nullable=True),
    sa.Column('low_system', sa.String(), nullable=True),
    sa.Column('low_code', sa.String(), nullable=True),
    sa.Column('high_value', sa.Numeric(), nullable=True),
    sa.Column('high_unit', sa.String(), nullable=True),
    sa.Column('high_system', sa.String(), nullable=True),
    sa.Column('high_code', sa.String(), nullable=True),
    sa.Column('type_system', sa.String(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_display', sa.String(), nullable=True),
    sa.Column('type_text', sa.String(), nullable=True),
    sa.Column('age_low_value', sa.Numeric(), nullable=True),
    sa.Column('age_low_unit', sa.String(), nullable=True),
    sa.Column('age_low_system', sa.String(), nullable=True),
    sa.Column('age_low_code', sa.String(), nullable=True),
    sa.Column('age_high_value', sa.Numeric(), nullable=True),
    sa.Column('age_high_unit', sa.String(), nullable=True),
    sa.Column('age_high_system', sa.String(), nullable=True),
    sa.Column('age_high_code', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['staging_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_reference_range_observation_id'), 'staging_observation_reference_range', ['observation_id'], unique=False)
    op.create_table('staging_observation_component_interpretation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('component_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['staging_observation_component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_component_interpretation_component_id'), 'staging_observation_component_interpretation', ['component_id'], unique=False)
    op.create_table('staging_observation_component_reference_range',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('component_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('low_value', sa.Numeric(), nullable=True),
    sa.Column('low_unit', sa.String(), nullable=True),
    sa.Column('low_system', sa.String(), nullable=True),
    sa.Column('low_code', sa.String(), nullable=True),
    sa.Column('high_value', sa.Numeric(), nullable=True),
    sa.Column('high_unit', sa.String(), nullable=True),
    sa.Column('high_system', sa.String(), nullable=True),
    sa.Column('high_code', sa.String(), nullable=True),
    sa.Column('type_system', sa.String(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_display', sa.String(), nullable=True),
    sa.Column('type_text', sa.String(), nullable=True),
    sa.Column('age_low_value', sa.Numeric(), nullable=True),
    sa.Column('age_low_unit', sa.String(), nullable=True),
    sa.Column('age_low_system', sa.String(), nullable=True),
    sa.Column('age_low_code', sa.String(), nullable=True),
    sa.Column('age_high_value', sa.Numeric(), nullable=True),
    sa.Column('age_high_unit', sa.String(), nullable=True),
    sa.Column('age_high_system', sa.String(), nullable=True),
    sa.Column('age_high_code', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['staging_observation_component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_component_reference_range_component_id'), 'staging_observation_component_reference_range', ['component_id'], unique=False)
    op.create_table('staging_observation_reference_range_applies_to',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reference_range_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reference_range_id'], ['staging_observation_reference_range.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_reference_range_applies_to_reference_range_id'), 'staging_observation_reference_range_applies_to', ['reference_range_id'], unique=False)
    op.create_table('staging_observation_component_reference_range_applies_to',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reference_range_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reference_range_id'], ['staging_observation_component_reference_range.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_observation_component_reference_range_applies_to_reference_range_id'), 'staging_observation_component_reference_range_applies_to', ['reference_range_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staging_observation_component_reference_range_applies_to_reference_range_id'), table_name='staging_observation_component_reference_range_applies_to')
    op.drop_table('staging_observation_component_reference_range_applies_to')
    op.drop_index(op.f('ix_staging_observation_reference_range_applies_to_reference_range_id'), table_name='staging_observation_reference_range_applies_to')
    op.drop_table('staging_observation_reference_range_applies_to')
    op.drop_index(op.f('ix_staging_observation_component_reference_range_component_id'), table_name='staging_observation_component_reference_range')
    op.drop_table('staging_observation_component_reference_range')
    op.drop_index(op.f('ix_staging_observation_component_interpretation_component_id'), table_name='staging_observation_component_interpretation')
    op.drop_table('staging_observation_component_interpretation')
    op.drop_index(op.f('ix_staging_observation_reference_range_observation_id'), table_name='staging_observation_reference_range')
    op.drop_table('staging_observation_reference_range')
    op.drop_index(op.f('ix_staging_observation_performer_observation_id'), table_name='staging_observation_performer')
    op.drop_table('staging_observation_performer')
    op.drop_index(op.f('ix_staging_observation_part_of_observation_id'), table_name='staging_observation_part_of')
    op.drop_table('staging_observation_part_of')
    op.drop_index(op.f('ix_staging_observation_note_observation_id'), table_name='staging_observation_note')
    op.drop_table('staging_observation_note')
    op.drop_index(op.f('ix_staging_observation_interpretation_observation_id'), table_name='staging_observation_interpretation')
    op.drop_table('staging_observation_interpretation')
    op.drop_index(op.f('ix_staging_observation_identifier_observation_id'), table_name='staging_observation_identifier')
    op.drop_table('staging_observation_identifier')
    op.drop_index(op.f('ix_staging_observation_has_member_observation_id'), table_name='staging_observation_has_member')
    op.drop_table('staging_observation_has_member')
    op.drop_index(op.f('ix_staging_observation_focus_observation_id'), table_name='staging_observation_focus')
    op.drop_table('staging_observation_focus')
    op.drop_index(op.f('ix_staging_observation_derived_from_observation_id'), table_name='staging_observation_derived_from')
    op.drop_table('staging_observation_derived_from')
    op.drop_index(op.f('ix_staging_observation_component_observation_id'), table_name='staging_observation_component')
    op.drop_table('staging_observation_component')
    op.drop_index(op.f('ix_staging_observation_category_observation_id'), table_name='staging_observation_category')
    op.drop_table('staging_observation_category')
    op.drop_index(op.f('ix_staging_observation_based_on_observation_id'), table_name='staging_observation_based_on')
    op.drop_table('staging_observation_based_on')
    op.drop_index(op.f('ix_staging_observation_user_id'), table_name='staging_observation')
    op.drop_index(op.f('ix_staging_observation_staging_medical_record_id'), table_name='staging_observation')
    op.drop_index(op.f('ix_staging_observation_org_id'), table_name='staging_observation')
    op.drop_index(op.f('ix_staging_observation_observation_id'), table_name='staging_observation')
    op.drop_index(op.f('ix_staging_observation_id'), table_name='staging_observation')
    op.drop_index(op.f('ix_staging_observation_encounter_id'), table_name='staging_observation')
    op.drop_table('staging_observation')
    op.drop_index(op.f('ix_staging_record_user_id'), table_name='staging_record')
    op.drop_index(op.f('ix_staging_record_status'), table_name='staging_record')
    op.drop_index(op.f('ix_staging_record_staging_medical_record_id'), table_name='staging_record')
    op.drop_index(op.f('ix_staging_record_service_request_id'), table_name='staging_record')
    op.drop_index(op.f('ix_staging_record_review_status'), table_name='staging_record')
    op.drop_index(op.f('ix_staging_record_patient_id'), table_name='staging_record')
    op.drop_index(op.f('ix_staging_record_org_id'), table_name='staging_record')
    op.drop_index(op.f('ix_staging_record_id'), table_name='staging_record')
    op.drop_index(op.f('ix_staging_record_file_id'), table_name='staging_record')
    op.drop_index(op.f('ix_staging_record_encounter_id'), table_name='staging_record')
    op.drop_index(op.f('ix_staging_record_diagnostic_report_id'), table_name='staging_record')
    op.drop_index(op.f('ix_staging_record_appointment_id'), table_name='staging_record')
    op.drop_table('staging_record')
    op.execute('DROP SEQUENCE IF EXISTS staging_medical_record_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS staging_observation_pub_seq')
    # ### end Alembic commands ###
