"""
Public API for the Appointment schemas package.

Import from here rather than from sub-modules to insulate callers from
internal reorganisation.
"""

from app.schemas.appointment.enums import AppointmentParticipantStatus, AppointmentStatus
from app.schemas.appointment.fhir_schemas import FhirAppointmentResponse, FhirBundleResponse
from app.schemas.appointment.input import (
    AppointmentAccountInput,
    AppointmentBasedOnInput,
    AppointmentClassInput,
    AppointmentCreateSchema,
    AppointmentIdentifierInput,
    AppointmentNoteInput,
    AppointmentParticipantInput,
    AppointmentParticipantTypeInput,
    AppointmentPatchSchema,
    AppointmentPatientInstructionInput,
    AppointmentReasonInput,
    AppointmentReplacesInput,
    AppointmentRequestedPeriodInput,
    AppointmentServiceCategoryInput,
    AppointmentServiceTypeInput,
    AppointmentSlotInput,
    AppointmentSpecialtyInput,
    AppointmentSupportingInformationInput,
    AppointmentVirtualServiceInput,
    ListAppointmentsSchema,
    MeAppointmentsSchema,
    RecurrenceMonthlyTemplateInput,
    RecurrenceTemplateInput,
    RecurrenceWeeklyTemplateInput,
    RecurrenceYearlyTemplateInput,
)
from app.schemas.appointment.response import (
    AppointmentResponse,
    PaginatedAppointmentResponse,
    PlainAppointmentAccount,
    PlainAppointmentBasedOn,
    PlainAppointmentClass,
    PlainAppointmentIdentifier,
    PlainAppointmentNote,
    PlainAppointmentParticipant,
    PlainAppointmentParticipantType,
    PlainAppointmentPatientInstruction,
    PlainAppointmentReason,
    PlainAppointmentRecurrenceTemplate,
    PlainAppointmentReplaces,
    PlainAppointmentRequestedPeriod,
    PlainAppointmentServiceCategory,
    PlainAppointmentServiceType,
    PlainAppointmentSlot,
    PlainAppointmentSpecialty,
    PlainAppointmentSupportingInformation,
    PlainAppointmentVirtualService,
)

__all__ = [
    # ── Enums ─────────────────────────────────────────────────────────────────
    "AppointmentStatus",
    "AppointmentParticipantStatus",
    # ── Input schemas (request body / query params) ───────────────────────────
    "AppointmentCreateSchema",
    "AppointmentPatchSchema",
    "ListAppointmentsSchema",
    "MeAppointmentsSchema",
    # Nested input schemas
    "AppointmentIdentifierInput",
    "AppointmentClassInput",
    "AppointmentServiceCategoryInput",
    "AppointmentServiceTypeInput",
    "AppointmentSpecialtyInput",
    "AppointmentReasonInput",
    "AppointmentSupportingInformationInput",
    "AppointmentSlotInput",
    "AppointmentBasedOnInput",
    "AppointmentReplacesInput",
    "AppointmentVirtualServiceInput",
    "AppointmentAccountInput",
    "AppointmentNoteInput",
    "AppointmentPatientInstructionInput",
    "AppointmentParticipantTypeInput",
    "AppointmentParticipantInput",
    "AppointmentRequestedPeriodInput",
    "RecurrenceWeeklyTemplateInput",
    "RecurrenceMonthlyTemplateInput",
    "RecurrenceYearlyTemplateInput",
    "RecurrenceTemplateInput",
    # ── Plain JSON response schemas (application/json) ─────────────────────────
    "AppointmentResponse",
    "PaginatedAppointmentResponse",
    "PlainAppointmentIdentifier",
    "PlainAppointmentClass",
    "PlainAppointmentServiceCategory",
    "PlainAppointmentServiceType",
    "PlainAppointmentSpecialty",
    "PlainAppointmentReason",
    "PlainAppointmentSupportingInformation",
    "PlainAppointmentSlot",
    "PlainAppointmentBasedOn",
    "PlainAppointmentReplaces",
    "PlainAppointmentVirtualService",
    "PlainAppointmentAccount",
    "PlainAppointmentNote",
    "PlainAppointmentPatientInstruction",
    "PlainAppointmentParticipantType",
    "PlainAppointmentParticipant",
    "PlainAppointmentRequestedPeriod",
    "PlainAppointmentRecurrenceTemplate",
    # ── FHIR R4 response schemas (application/fhir+json) ──────────────────────
    "FhirAppointmentResponse",
    "FhirBundleResponse",
]
