"""add_practitioner_role_tables

Revision ID: 1211bf284768
Revises: 0c955f223823
Create Date: 2026-05-15 13:19:08.315540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1211bf284768'
down_revision: Union[str, None] = '0c955f223823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop role/specialty columns and the stale enum type first — the type name
    # collides with the new practitioner_role table and must be gone before CREATE TABLE.
    op.drop_column('practitioner', 'specialty')
    op.drop_column('practitioner', 'role')
    op.execute("DROP TYPE IF EXISTS practitioner_role")

    # Create shared enum types that don't yet exist in the DB.
    # identifier_use already exists (created by a previous migration).
    op.execute("CREATE TYPE address_use AS ENUM ('home', 'work', 'temp', 'old', 'billing')")
    op.execute("CREATE TYPE address_type AS ENUM ('postal', 'physical', 'both')")
    op.execute("CREATE TYPE human_name_use AS ENUM ('usual', 'official', 'temp', 'nickname', 'anonymous', 'old', 'maiden')")
    op.execute("CREATE TYPE contact_point_system AS ENUM ('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other')")
    op.execute("CREATE TYPE contact_point_use AS ENUM ('home', 'work', 'temp', 'old', 'mobile')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practitioner_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.Integer(), server_default=sa.text("nextval('practitioner_role_id_seq')"), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('practitioner_fk_id', sa.Integer(), nullable=True),
    sa.Column('practitioner_ref_id', sa.Integer(), nullable=True),
    sa.Column('practitioner_display', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('organization_display', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_fk_id'], ['practitioner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_id'), 'practitioner_role', ['id'], unique=False)
    op.create_index(op.f('ix_practitioner_role_practitioner_fk_id'), 'practitioner_role', ['practitioner_fk_id'], unique=False)
    op.create_index(op.f('ix_practitioner_role_practitioner_role_id'), 'practitioner_role', ['practitioner_role_id'], unique=True)
    op.create_index(op.f('ix_practitioner_role_user_id'), 'practitioner_role', ['user_id'], unique=False)
    op.create_table('practitioner_role_availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_availability_practitioner_role_id'), 'practitioner_role_availability', ['practitioner_role_id'], unique=False)
    op.create_table('practitioner_role_characteristic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_characteristic_practitioner_role_id'), 'practitioner_role_characteristic', ['practitioner_role_id'], unique=False)
    op.create_table('practitioner_role_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_code_practitioner_role_id'), 'practitioner_role_code', ['practitioner_role_id'], unique=False)
    op.create_table('practitioner_role_communication',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_communication_practitioner_role_id'), 'practitioner_role_communication', ['practitioner_role_id'], unique=False)
    op.create_table('practitioner_role_contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('purpose_system', sa.String(), nullable=True),
    sa.Column('purpose_code', sa.String(), nullable=True),
    sa.Column('purpose_display', sa.String(), nullable=True),
    sa.Column('purpose_text', sa.String(), nullable=True),
    sa.Column('address_use', postgresql.ENUM('home', 'work', 'temp', 'old', 'billing', name='address_use', create_type=False), nullable=True),
    sa.Column('address_type', postgresql.ENUM('postal', 'physical', 'both', name='address_type', create_type=False), nullable=True),
    sa.Column('address_text', sa.String(), nullable=True),
    sa.Column('address_line', sa.Text(), nullable=True),
    sa.Column('address_city', sa.String(), nullable=True),
    sa.Column('address_district', sa.String(), nullable=True),
    sa.Column('address_state', sa.String(), nullable=True),
    sa.Column('address_postal_code', sa.String(), nullable=True),
    sa.Column('address_country', sa.String(), nullable=True),
    sa.Column('address_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('organization_display', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_contact_practitioner_role_id'), 'practitioner_role_contact', ['practitioner_role_id'], unique=False)
    op.create_table('practitioner_role_endpoint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('endpoint_ref_id', sa.Integer(), nullable=True),
    sa.Column('endpoint_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_endpoint_practitioner_role_id'), 'practitioner_role_endpoint', ['practitioner_role_id'], unique=False)
    op.create_table('practitioner_role_healthcare_service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('service_ref_id', sa.Integer(), nullable=True),
    sa.Column('service_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_healthcare_service_practitioner_role_id'), 'practitioner_role_healthcare_service', ['practitioner_role_id'], unique=False)
    op.create_table('practitioner_role_identifier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True),
    sa.Column('type_system', sa.String(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_display', sa.String(), nullable=True),
    sa.Column('type_text', sa.String(), nullable=True),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigner', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_identifier_practitioner_role_id'), 'practitioner_role_identifier', ['practitioner_role_id'], unique=False)
    op.create_table('practitioner_role_location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('location_ref_id', sa.Integer(), nullable=True),
    sa.Column('location_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_location_practitioner_role_id'), 'practitioner_role_location', ['practitioner_role_id'], unique=False)
    op.create_table('practitioner_role_specialty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_specialty_practitioner_role_id'), 'practitioner_role_specialty', ['practitioner_role_id'], unique=False)
    op.create_table('practitioner_role_availability_time',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('availability_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('days_of_week', sa.Text(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=True),
    sa.Column('available_start_time', sa.String(), nullable=True),
    sa.Column('available_end_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['availability_id'], ['practitioner_role_availability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_availability_time_availability_id'), 'practitioner_role_availability_time', ['availability_id'], unique=False)
    op.create_table('practitioner_role_contact_name',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('use', postgresql.ENUM('usual', 'official', 'temp', 'nickname', 'anonymous', 'old', 'maiden', name='human_name_use', create_type=False), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('given', sa.Text(), nullable=True),
    sa.Column('prefix', sa.Text(), nullable=True),
    sa.Column('suffix', sa.Text(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['practitioner_role_contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_contact_name_contact_id'), 'practitioner_role_contact_name', ['contact_id'], unique=False)
    op.create_table('practitioner_role_contact_telecom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('system', postgresql.ENUM('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system', create_type=False), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('use', postgresql.ENUM('home', 'work', 'temp', 'old', 'mobile', name='contact_point_use', create_type=False), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['practitioner_role_contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_contact_telecom_contact_id'), 'practitioner_role_contact_telecom', ['contact_id'], unique=False)
    op.create_table('practitioner_role_not_available_time',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('availability_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('during_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('during_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['availability_id'], ['practitioner_role_availability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_not_available_time_availability_id'), 'practitioner_role_not_available_time', ['availability_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practitioner', sa.Column('role', postgresql.ENUM('doctor', 'nurse', name='practitioner_role'), autoincrement=False, nullable=True))
    op.add_column('practitioner', sa.Column('specialty', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_practitioner_role_not_available_time_availability_id'), table_name='practitioner_role_not_available_time')
    op.drop_table('practitioner_role_not_available_time')
    op.drop_index(op.f('ix_practitioner_role_contact_telecom_contact_id'), table_name='practitioner_role_contact_telecom')
    op.drop_table('practitioner_role_contact_telecom')
    op.drop_index(op.f('ix_practitioner_role_contact_name_contact_id'), table_name='practitioner_role_contact_name')
    op.drop_table('practitioner_role_contact_name')
    op.drop_index(op.f('ix_practitioner_role_availability_time_availability_id'), table_name='practitioner_role_availability_time')
    op.drop_table('practitioner_role_availability_time')
    op.drop_index(op.f('ix_practitioner_role_specialty_practitioner_role_id'), table_name='practitioner_role_specialty')
    op.drop_table('practitioner_role_specialty')
    op.drop_index(op.f('ix_practitioner_role_location_practitioner_role_id'), table_name='practitioner_role_location')
    op.drop_table('practitioner_role_location')
    op.drop_index(op.f('ix_practitioner_role_identifier_practitioner_role_id'), table_name='practitioner_role_identifier')
    op.drop_table('practitioner_role_identifier')
    op.drop_index(op.f('ix_practitioner_role_healthcare_service_practitioner_role_id'), table_name='practitioner_role_healthcare_service')
    op.drop_table('practitioner_role_healthcare_service')
    op.drop_index(op.f('ix_practitioner_role_endpoint_practitioner_role_id'), table_name='practitioner_role_endpoint')
    op.drop_table('practitioner_role_endpoint')
    op.drop_index(op.f('ix_practitioner_role_contact_practitioner_role_id'), table_name='practitioner_role_contact')
    op.drop_table('practitioner_role_contact')
    op.drop_index(op.f('ix_practitioner_role_communication_practitioner_role_id'), table_name='practitioner_role_communication')
    op.drop_table('practitioner_role_communication')
    op.drop_index(op.f('ix_practitioner_role_code_practitioner_role_id'), table_name='practitioner_role_code')
    op.drop_table('practitioner_role_code')
    op.drop_index(op.f('ix_practitioner_role_characteristic_practitioner_role_id'), table_name='practitioner_role_characteristic')
    op.drop_table('practitioner_role_characteristic')
    op.drop_index(op.f('ix_practitioner_role_availability_practitioner_role_id'), table_name='practitioner_role_availability')
    op.drop_table('practitioner_role_availability')
    op.drop_index(op.f('ix_practitioner_role_user_id'), table_name='practitioner_role')
    op.drop_index(op.f('ix_practitioner_role_practitioner_role_id'), table_name='practitioner_role')
    op.drop_index(op.f('ix_practitioner_role_practitioner_fk_id'), table_name='practitioner_role')
    op.drop_index(op.f('ix_practitioner_role_id'), table_name='practitioner_role')
    op.drop_table('practitioner_role')

    # Drop the shared enum types created in upgrade()
    op.execute("DROP TYPE IF EXISTS contact_point_use")
    op.execute("DROP TYPE IF EXISTS contact_point_system")
    op.execute("DROP TYPE IF EXISTS human_name_use")
    op.execute("DROP TYPE IF EXISTS address_type")
    op.execute("DROP TYPE IF EXISTS address_use")
    # ### end Alembic commands ###
