"""appointment_r5_updates

Revision ID: 40aa37fd680f
Revises: 3fe34d49a2a1
Create Date: 2026-05-15 14:29:44.785484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40aa37fd680f'
down_revision: Union[str, None] = '3fe34d49a2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new enum values to appointment_participant_actor_type
    op.execute("ALTER TYPE appointment_participant_actor_type ADD VALUE IF NOT EXISTS 'Group'")
    op.execute("ALTER TYPE appointment_participant_actor_type ADD VALUE IF NOT EXISTS 'CareTeam'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('account_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_account_appointment_id'), 'appointment_account', ['appointment_id'], unique=False)
    op.create_table('appointment_class',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_class_appointment_id'), 'appointment_class', ['appointment_id'], unique=False)
    op.create_table('appointment_note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('author_string', sa.String(), nullable=True),
    sa.Column('author_reference_type', sa.String(), nullable=True),
    sa.Column('author_reference_id', sa.Integer(), nullable=True),
    sa.Column('author_reference_display', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_note_appointment_id'), 'appointment_note', ['appointment_id'], unique=False)
    op.create_table('appointment_patient_instruction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_patient_instruction_appointment_id'), 'appointment_patient_instruction', ['appointment_id'], unique=False)
    op.create_table('appointment_reason',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_reason_appointment_id'), 'appointment_reason', ['appointment_id'], unique=False)
    op.create_table('appointment_replaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('replaced_appointment_id', sa.Integer(), nullable=True),
    sa.Column('replaced_appointment_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_replaces_appointment_id'), 'appointment_replaces', ['appointment_id'], unique=False)
    op.create_table('appointment_virtual_service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('channel_type_system', sa.String(), nullable=True),
    sa.Column('channel_type_code', sa.String(), nullable=True),
    sa.Column('channel_type_display', sa.String(), nullable=True),
    sa.Column('address_url', sa.String(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('session_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_virtual_service_appointment_id'), 'appointment_virtual_service', ['appointment_id'], unique=False)
    op.drop_index(op.f('ix_appointment_reason_reference_appointment_id'), table_name='appointment_reason_reference')
    op.drop_table('appointment_reason_reference')
    op.drop_index(op.f('ix_appointment_reason_code_appointment_id'), table_name='appointment_reason_code')
    op.drop_table('appointment_reason_code')
    op.add_column('appointment', sa.Column('cancellation_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointment', sa.Column('priority_system', sa.String(), nullable=True))
    op.add_column('appointment', sa.Column('priority_code', sa.String(), nullable=True))
    op.add_column('appointment', sa.Column('priority_display', sa.String(), nullable=True))
    op.add_column('appointment', sa.Column('priority_text', sa.String(), nullable=True))
    op.add_column('appointment', sa.Column('previous_appointment_id', sa.Integer(), nullable=True))
    op.add_column('appointment', sa.Column('previous_appointment_display', sa.String(), nullable=True))
    op.add_column('appointment', sa.Column('originating_appointment_id', sa.Integer(), nullable=True))
    op.add_column('appointment', sa.Column('originating_appointment_display', sa.String(), nullable=True))
    op.add_column('appointment', sa.Column('recurrence_id', sa.Integer(), nullable=True))
    op.add_column('appointment', sa.Column('occurrence_changed', sa.Boolean(), nullable=True))
    op.drop_column('appointment', 'comment')
    op.drop_column('appointment', 'patient_instruction')
    op.drop_column('appointment', 'priority_value')
    op.alter_column('appointment_participant', 'required',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="CASE WHEN required = 'required' THEN true WHEN required = 'optional' OR required = 'information-only' THEN false ELSE NULL END")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment_participant', 'required',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('appointment', sa.Column('priority_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('patient_instruction', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('appointment', 'occurrence_changed')
    op.drop_column('appointment', 'recurrence_id')
    op.drop_column('appointment', 'originating_appointment_display')
    op.drop_column('appointment', 'originating_appointment_id')
    op.drop_column('appointment', 'previous_appointment_display')
    op.drop_column('appointment', 'previous_appointment_id')
    op.drop_column('appointment', 'priority_text')
    op.drop_column('appointment', 'priority_display')
    op.drop_column('appointment', 'priority_code')
    op.drop_column('appointment', 'priority_system')
    op.drop_column('appointment', 'cancellation_date')
    op.create_table('appointment_reason_code',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name=op.f('appointment_reason_code_appointment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointment_reason_code_pkey'))
    )
    op.create_index(op.f('ix_appointment_reason_code_appointment_id'), 'appointment_reason_code', ['appointment_id'], unique=False)
    op.create_table('appointment_reason_reference',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name=op.f('appointment_reason_reference_appointment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointment_reason_reference_pkey'))
    )
    op.create_index(op.f('ix_appointment_reason_reference_appointment_id'), 'appointment_reason_reference', ['appointment_id'], unique=False)
    op.drop_index(op.f('ix_appointment_virtual_service_appointment_id'), table_name='appointment_virtual_service')
    op.drop_table('appointment_virtual_service')
    op.drop_index(op.f('ix_appointment_replaces_appointment_id'), table_name='appointment_replaces')
    op.drop_table('appointment_replaces')
    op.drop_index(op.f('ix_appointment_reason_appointment_id'), table_name='appointment_reason')
    op.drop_table('appointment_reason')
    op.drop_index(op.f('ix_appointment_patient_instruction_appointment_id'), table_name='appointment_patient_instruction')
    op.drop_table('appointment_patient_instruction')
    op.drop_index(op.f('ix_appointment_note_appointment_id'), table_name='appointment_note')
    op.drop_table('appointment_note')
    op.drop_index(op.f('ix_appointment_class_appointment_id'), table_name='appointment_class')
    op.drop_table('appointment_class')
    op.drop_index(op.f('ix_appointment_account_appointment_id'), table_name='appointment_account')
    op.drop_table('appointment_account')
    # ### end Alembic commands ###
