"""practitioner_qualification_status

Revision ID: 8d6f48e4ac7e
Revises: 13e0246ea539
Create Date: 2026-05-15 14:02:50.426518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6f48e4ac7e'
down_revision: Union[str, None] = '13e0246ea539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practitioner_qualification', sa.Column('status_system', sa.String(), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('status_code', sa.String(), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('status_display', sa.String(), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('status_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practitioner_qualification', 'status_text')
    op.drop_column('practitioner_qualification', 'status_display')
    op.drop_column('practitioner_qualification', 'status_code')
    op.drop_column('practitioner_qualification', 'status_system')
    # ### end Alembic commands ###
