"""refactor_practitioner_fhir_r4

Revision ID: a2f8dd5bb187
Revises: cc94e2d5ff48
Create Date: 2026-05-14 21:55:47.831815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2f8dd5bb187'
down_revision: Union[str, None] = 'cc94e2d5ff48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_communication',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('language_system', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('language_display', sa.String(), nullable=True),
    sa.Column('language_text', sa.String(), nullable=True),
    sa.Column('preferred', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_communication_patient_id'), 'patient_communication', ['patient_id'], unique=False)
    op.create_table('patient_contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('name_use', sa.String(), nullable=True),
    sa.Column('name_text', sa.String(), nullable=True),
    sa.Column('name_family', sa.String(), nullable=True),
    sa.Column('name_given', sa.Text(), nullable=True),
    sa.Column('name_prefix', sa.Text(), nullable=True),
    sa.Column('name_suffix', sa.Text(), nullable=True),
    sa.Column('address_use', sa.String(), nullable=True),
    sa.Column('address_type', sa.String(), nullable=True),
    sa.Column('address_text', sa.String(), nullable=True),
    sa.Column('address_line', sa.Text(), nullable=True),
    sa.Column('address_city', sa.String(), nullable=True),
    sa.Column('address_district', sa.String(), nullable=True),
    sa.Column('address_state', sa.String(), nullable=True),
    sa.Column('address_postal_code', sa.String(), nullable=True),
    sa.Column('address_country', sa.String(), nullable=True),
    sa.Column('address_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('organization_display', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_contact_patient_id'), 'patient_contact', ['patient_id'], unique=False)
    op.create_table('patient_general_practitioner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_type', sa.Enum('ORGANIZATION', 'PRACTITIONER', 'PRACTITIONER_ROLE', name='patient_gp_type'), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_general_practitioner_patient_id'), 'patient_general_practitioner', ['patient_id'], unique=False)
    op.create_table('patient_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('other_type', sa.Enum('PATIENT', 'RELATED_PERSON', name='patient_link_other_type'), nullable=True),
    sa.Column('other_id', sa.Integer(), nullable=True),
    sa.Column('other_display', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('REPLACED_BY', 'REPLACES', 'REFER', 'SEEALSO', name='patient_link_type'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_link_patient_id'), 'patient_link', ['patient_id'], unique=False)
    op.create_table('patient_name',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('use', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('given', sa.Text(), nullable=True),
    sa.Column('prefix', sa.Text(), nullable=True),
    sa.Column('suffix', sa.Text(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_name_patient_id'), 'patient_name', ['patient_id'], unique=False)
    op.create_table('patient_photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('creation', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_photo_patient_id'), 'patient_photo', ['patient_id'], unique=False)
    op.create_table('practitioner_communication',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practitioner_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('language_system', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('language_display', sa.String(), nullable=True),
    sa.Column('language_text', sa.String(), nullable=True),
    sa.Column('preferred', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_communication_practitioner_id'), 'practitioner_communication', ['practitioner_id'], unique=False)
    op.create_table('practitioner_name',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practitioner_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('use', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('given', sa.Text(), nullable=True),
    sa.Column('prefix', sa.Text(), nullable=True),
    sa.Column('suffix', sa.Text(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_name_practitioner_id'), 'practitioner_name', ['practitioner_id'], unique=False)
    op.create_table('practitioner_photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practitioner_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('creation', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_photo_practitioner_id'), 'practitioner_photo', ['practitioner_id'], unique=False)
    op.create_table('patient_contact_relationship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['patient_contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_contact_relationship_contact_id'), 'patient_contact_relationship', ['contact_id'], unique=False)
    op.create_table('patient_contact_telecom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('use', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['patient_contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_contact_telecom_contact_id'), 'patient_contact_telecom', ['contact_id'], unique=False)
    # Drop FK constraints referencing codeable_concept BEFORE dropping the table
    op.drop_constraint(op.f('patient_identifier_type_id_fkey'), 'patient_identifier', type_='foreignkey')
    op.drop_constraint(op.f('practitioner_identifier_type_id_fkey'), 'practitioner_identifier', type_='foreignkey')
    op.drop_index(op.f('ix_coding_codeable_concept_id'), table_name='coding')
    op.drop_table('coding')
    op.drop_table('codeable_concept')
    op.add_column('patient', sa.Column('marital_status_system', sa.String(), nullable=True))
    op.add_column('patient', sa.Column('marital_status_code', sa.String(), nullable=True))
    op.add_column('patient', sa.Column('marital_status_display', sa.String(), nullable=True))
    op.add_column('patient', sa.Column('marital_status_text', sa.String(), nullable=True))
    op.add_column('patient', sa.Column('multiple_birth_boolean', sa.Boolean(), nullable=True))
    op.add_column('patient', sa.Column('multiple_birth_integer', sa.Integer(), nullable=True))
    op.add_column('patient', sa.Column('managing_organization_id', sa.Integer(), nullable=True))
    op.add_column('patient', sa.Column('managing_organization_display', sa.String(), nullable=True))
    op.execute("CREATE TYPE patient_gender AS ENUM ('MALE', 'FEMALE', 'OTHER', 'UNKNOWN')")
    op.execute(
        "ALTER TABLE patient ALTER COLUMN gender TYPE patient_gender "
        "USING upper(gender::text)::patient_gender"
    )
    op.execute("DROP TYPE IF EXISTS gender_type")
    op.create_index(op.f('ix_patient_org_id'), 'patient', ['org_id'], unique=False)
    op.drop_column('patient', 'given_name')
    op.drop_column('patient', 'family_name')
    op.add_column('patient_address', sa.Column('org_id', sa.String(), nullable=True))
    op.add_column('patient_address', sa.Column('use', sa.String(), nullable=True))
    op.add_column('patient_address', sa.Column('type', sa.String(), nullable=True))
    op.add_column('patient_address', sa.Column('text', sa.String(), nullable=True))
    op.add_column('patient_address', sa.Column('district', sa.String(), nullable=True))
    op.add_column('patient_address', sa.Column('period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('patient_address', sa.Column('period_end', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('patient_address', 'line',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('patient_identifier', sa.Column('org_id', sa.String(), nullable=True))
    op.add_column('patient_identifier', sa.Column('type_system', sa.String(), nullable=True))
    op.add_column('patient_identifier', sa.Column('type_code', sa.String(), nullable=True))
    op.add_column('patient_identifier', sa.Column('type_display', sa.String(), nullable=True))
    op.alter_column('patient_identifier', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('patient_identifier', 'type_id')
    op.add_column('patient_telecom', sa.Column('org_id', sa.String(), nullable=True))
    op.add_column('patient_telecom', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('patient_telecom', sa.Column('period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('patient_telecom', sa.Column('period_end', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('practitioner', 'given_name')
    op.drop_column('practitioner', 'family_name')
    op.add_column('practitioner_address', sa.Column('period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_address', sa.Column('period_end', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('practitioner_address', 'line',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('practitioner_identifier', sa.Column('type_system', sa.String(), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('type_code', sa.String(), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('type_display', sa.String(), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('type_text', sa.String(), nullable=True))
    op.drop_column('practitioner_identifier', 'type_id')
    op.add_column('practitioner_qualification', sa.Column('code_system', sa.String(), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('code_code', sa.String(), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('code_display', sa.String(), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('issuer_id', sa.Integer(), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('issuer_display', sa.String(), nullable=True))
    op.drop_column('practitioner_qualification', 'issuer')
    op.add_column('practitioner_telecom', sa.Column('period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_telecom', sa.Column('period_end', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practitioner_telecom', 'period_end')
    op.drop_column('practitioner_telecom', 'period_start')
    op.add_column('practitioner_qualification', sa.Column('issuer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('practitioner_qualification', 'issuer_display')
    op.drop_column('practitioner_qualification', 'issuer_id')
    op.drop_column('practitioner_qualification', 'period_end')
    op.drop_column('practitioner_qualification', 'period_start')
    op.drop_column('practitioner_qualification', 'code_display')
    op.drop_column('practitioner_qualification', 'code_code')
    op.drop_column('practitioner_qualification', 'code_system')
    op.add_column('practitioner_identifier', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('practitioner_identifier_type_id_fkey'), 'practitioner_identifier', 'codeable_concept', ['type_id'], ['id'])
    op.drop_column('practitioner_identifier', 'type_text')
    op.drop_column('practitioner_identifier', 'type_display')
    op.drop_column('practitioner_identifier', 'type_code')
    op.drop_column('practitioner_identifier', 'type_system')
    op.alter_column('practitioner_address', 'line',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('practitioner_address', 'period_end')
    op.drop_column('practitioner_address', 'period_start')
    op.add_column('practitioner', sa.Column('family_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('practitioner', sa.Column('given_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patient_telecom', 'period_end')
    op.drop_column('patient_telecom', 'period_start')
    op.drop_column('patient_telecom', 'rank')
    op.drop_column('patient_telecom', 'org_id')
    op.add_column('patient_identifier', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('patient_identifier_type_id_fkey'), 'patient_identifier', 'codeable_concept', ['type_id'], ['id'])
    op.alter_column('patient_identifier', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('patient_identifier', 'type_display')
    op.drop_column('patient_identifier', 'type_code')
    op.drop_column('patient_identifier', 'type_system')
    op.drop_column('patient_identifier', 'org_id')
    op.alter_column('patient_address', 'line',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('patient_address', 'period_end')
    op.drop_column('patient_address', 'period_start')
    op.drop_column('patient_address', 'district')
    op.drop_column('patient_address', 'text')
    op.drop_column('patient_address', 'type')
    op.drop_column('patient_address', 'use')
    op.drop_column('patient_address', 'org_id')
    op.add_column('patient', sa.Column('family_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient', sa.Column('given_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_patient_org_id'), table_name='patient')
    op.alter_column('patient', 'gender',
               existing_type=sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNKNOWN', name='patient_gender'),
               type_=postgresql.ENUM('male', 'female', 'other', 'unknown', name='gender_type'),
               existing_nullable=True)
    op.drop_column('patient', 'managing_organization_display')
    op.drop_column('patient', 'managing_organization_id')
    op.drop_column('patient', 'multiple_birth_integer')
    op.drop_column('patient', 'multiple_birth_boolean')
    op.drop_column('patient', 'marital_status_text')
    op.drop_column('patient', 'marital_status_display')
    op.drop_column('patient', 'marital_status_code')
    op.drop_column('patient', 'marital_status_system')
    op.create_table('codeable_concept',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('codeable_concept_pkey'))
    )
    op.create_table('coding',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codeable_concept_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_selected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['codeable_concept_id'], ['codeable_concept.id'], name=op.f('coding_codeable_concept_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('coding_pkey'))
    )
    op.create_index(op.f('ix_coding_codeable_concept_id'), 'coding', ['codeable_concept_id'], unique=False)
    op.drop_index(op.f('ix_patient_contact_telecom_contact_id'), table_name='patient_contact_telecom')
    op.drop_table('patient_contact_telecom')
    op.drop_index(op.f('ix_patient_contact_relationship_contact_id'), table_name='patient_contact_relationship')
    op.drop_table('patient_contact_relationship')
    op.drop_index(op.f('ix_practitioner_photo_practitioner_id'), table_name='practitioner_photo')
    op.drop_table('practitioner_photo')
    op.drop_index(op.f('ix_practitioner_name_practitioner_id'), table_name='practitioner_name')
    op.drop_table('practitioner_name')
    op.drop_index(op.f('ix_practitioner_communication_practitioner_id'), table_name='practitioner_communication')
    op.drop_table('practitioner_communication')
    op.drop_index(op.f('ix_patient_photo_patient_id'), table_name='patient_photo')
    op.drop_table('patient_photo')
    op.drop_index(op.f('ix_patient_name_patient_id'), table_name='patient_name')
    op.drop_table('patient_name')
    op.drop_index(op.f('ix_patient_link_patient_id'), table_name='patient_link')
    op.drop_table('patient_link')
    op.drop_index(op.f('ix_patient_general_practitioner_patient_id'), table_name='patient_general_practitioner')
    op.drop_table('patient_general_practitioner')
    op.drop_index(op.f('ix_patient_contact_patient_id'), table_name='patient_contact')
    op.drop_table('patient_contact')
    op.drop_index(op.f('ix_patient_communication_patient_id'), table_name='patient_communication')
    op.drop_table('patient_communication')
    # ### end Alembic commands ###
