"""add_healthcare_service_tables

Revision ID: eccaa97a802e
Revises: aba0afc11c5c
Create Date: 2026-05-17 10:50:28.942108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eccaa97a802e'
down_revision: Union[str, None] = 'aba0afc11c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
