"""refactor_encounter_fhir_r4

Revision ID: fe58b342c8f0
Revises: a2f8dd5bb187
Create Date: 2026-05-14 22:10:26.039476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe58b342c8f0'
down_revision: Union[str, None] = 'a2f8dd5bb187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('account_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_account_encounter_id'), 'encounter_account', ['encounter_id'], unique=False)
    op.create_table('encounter_appointment_ref',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('appointment_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_appointment_ref_encounter_id'), 'encounter_appointment_ref', ['encounter_id'], unique=False)
    op.create_table('encounter_based_on',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_type', sa.Enum('SERVICE_REQUEST', name='encounter_based_on_reference_type'), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_based_on_encounter_id'), 'encounter_based_on', ['encounter_id'], unique=False)
    op.create_table('encounter_class_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('class_system', sa.String(), nullable=True),
    sa.Column('class_version', sa.String(), nullable=True),
    sa.Column('class_code', sa.String(), nullable=True),
    sa.Column('class_display', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_class_history_encounter_id'), 'encounter_class_history', ['encounter_id'], unique=False)
    op.create_table('encounter_episode_of_care',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('episode_of_care_id', sa.Integer(), nullable=True),
    sa.Column('display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_episode_of_care_encounter_id'), 'encounter_episode_of_care', ['encounter_id'], unique=False)
    op.create_table('encounter_hosp_diet_preference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_hosp_diet_preference_encounter_id'), 'encounter_hosp_diet_preference', ['encounter_id'], unique=False)
    op.create_table('encounter_hosp_special_arrangement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_hosp_special_arrangement_encounter_id'), 'encounter_hosp_special_arrangement', ['encounter_id'], unique=False)
    op.create_table('encounter_hosp_special_courtesy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_hosp_special_courtesy_encounter_id'), 'encounter_hosp_special_courtesy', ['encounter_id'], unique=False)
    op.create_table('encounter_identifier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('use', sa.String(), nullable=True),
    sa.Column('type_system', sa.String(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_display', sa.String(), nullable=True),
    sa.Column('type_text', sa.String(), nullable=True),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigner', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_identifier_encounter_id'), 'encounter_identifier', ['encounter_id'], unique=False)
    op.create_table('encounter_reason_reference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_reason_reference_encounter_id'), 'encounter_reason_reference', ['encounter_id'], unique=False)
    op.create_table('encounter_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_status_history_encounter_id'), 'encounter_status_history', ['encounter_id'], unique=False)
    op.create_table('encounter_participant_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['encounter_participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_participant_type_participant_id'), 'encounter_participant_type', ['participant_id'], unique=False)
    op.drop_index(op.f('ix_based_on_encounter_id'), table_name='based_on')
    op.drop_table('based_on')
    op.add_column('encounter', sa.Column('class_system', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('class_version', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('class_display', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('service_type_system', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('service_type_code', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('service_type_display', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('service_type_text', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('priority_system', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('priority_code', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('priority_display', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('priority_text', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('length_value', sa.Float(), nullable=True))
    op.add_column('encounter', sa.Column('length_comparator', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('length_unit', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('length_system', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('length_code', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_pre_admission_identifier_system', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_pre_admission_identifier_value', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_origin_type', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_origin_id', sa.Integer(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_origin_display', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_admit_source_system', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_admit_source_code', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_admit_source_display', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_admit_source_text', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_re_admission_system', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_re_admission_code', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_re_admission_display', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_re_admission_text', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_destination_type', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_destination_id', sa.Integer(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_destination_display', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_discharge_disposition_system', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_discharge_disposition_code', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_discharge_disposition_display', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hosp_discharge_disposition_text', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('service_provider_id', sa.Integer(), nullable=True))
    op.add_column('encounter', sa.Column('service_provider_display', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('part_of_id', sa.Integer(), nullable=True))
    # status: replace old R5 uppercase enum with R4 lowercase enum
    op.execute("CREATE TYPE encounter_status AS ENUM ('planned', 'arrived', 'triaged', 'in_progress', 'onleave', 'finished', 'cancelled', 'entered_in_error', 'unknown')")
    op.execute("ALTER TABLE encounter ALTER COLUMN status TYPE encounter_status USING lower(status::text)::encounter_status")
    op.execute("DROP TYPE IF EXISTS encounterstatus")

    # class_code: convert from old enum to plain string
    op.execute("ALTER TABLE encounter ALTER COLUMN class_code TYPE varchar USING class_code::varchar")
    op.execute("DROP TYPE IF EXISTS encounterclass")

    op.drop_column('encounter', 'priority')
    op.execute("CREATE TYPE encounter_diagnosis_condition_type AS ENUM ('CONDITION', 'PROCEDURE')")
    op.add_column('encounter_diagnosis', sa.Column('condition_type', sa.Enum('CONDITION', 'PROCEDURE', name='encounter_diagnosis_condition_type', create_type=False), nullable=True))
    op.add_column('encounter_diagnosis', sa.Column('condition_id', sa.Integer(), nullable=True))
    op.add_column('encounter_diagnosis', sa.Column('condition_display', sa.String(), nullable=True))
    op.add_column('encounter_diagnosis', sa.Column('use_system', sa.String(), nullable=True))
    op.add_column('encounter_diagnosis', sa.Column('use_code', sa.String(), nullable=True))
    op.add_column('encounter_diagnosis', sa.Column('use_display', sa.String(), nullable=True))
    op.execute("ALTER TABLE encounter_diagnosis ALTER COLUMN rank TYPE integer USING rank::integer")
    op.drop_column('encounter_diagnosis', 'condition_reference')
    op.add_column('encounter_location', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('encounter_location', sa.Column('location_display', sa.String(), nullable=True))
    op.add_column('encounter_location', sa.Column('physical_type_system', sa.String(), nullable=True))
    op.add_column('encounter_location', sa.Column('physical_type_code', sa.String(), nullable=True))
    op.add_column('encounter_location', sa.Column('physical_type_display', sa.String(), nullable=True))
    op.add_column('encounter_location', sa.Column('physical_type_text', sa.String(), nullable=True))
    # location status: varchar → enum
    op.execute("CREATE TYPE encounter_location_status AS ENUM ('planned', 'active', 'reserved', 'completed')")
    op.execute("ALTER TABLE encounter_location ALTER COLUMN status TYPE encounter_location_status USING status::text::encounter_location_status")
    op.drop_column('encounter_location', 'location_reference')
    op.execute("CREATE TYPE encounter_participant_reference_type AS ENUM ('PRACTITIONER', 'PRACTITIONER_ROLE', 'RELATED_PERSON')")
    op.add_column('encounter_participant', sa.Column('individual_type', sa.Enum('PRACTITIONER', 'PRACTITIONER_ROLE', 'RELATED_PERSON', name='encounter_participant_reference_type', create_type=False), nullable=True))
    op.add_column('encounter_participant', sa.Column('individual_id', sa.Integer(), nullable=True))
    op.add_column('encounter_participant', sa.Column('individual_display', sa.String(), nullable=True))
    op.drop_column('encounter_participant', 'type_text')
    op.drop_column('encounter_participant', 'reference_type')
    op.drop_column('encounter_participant', 'individual_reference')
    # drop old enum types that are no longer used
    op.execute("DROP TYPE IF EXISTS participant_reference_type")
    op.execute("DROP TYPE IF EXISTS based_on_reference_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounter_participant', sa.Column('individual_reference', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('encounter_participant', sa.Column('reference_type', postgresql.ENUM('PATIENT', 'PRACTITIONER', 'PRACTITIONER_ROLE', 'RELATED_PERSON', name='participant_reference_type'), autoincrement=False, nullable=True))
    op.add_column('encounter_participant', sa.Column('type_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('encounter_participant', 'individual_display')
    op.drop_column('encounter_participant', 'individual_id')
    op.drop_column('encounter_participant', 'individual_type')
    op.add_column('encounter_location', sa.Column('location_reference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('encounter_location', 'status',
               existing_type=sa.Enum('planned', 'active', 'reserved', 'completed', name='encounter_location_status'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('encounter_location', 'physical_type_text')
    op.drop_column('encounter_location', 'physical_type_display')
    op.drop_column('encounter_location', 'physical_type_code')
    op.drop_column('encounter_location', 'physical_type_system')
    op.drop_column('encounter_location', 'location_display')
    op.drop_column('encounter_location', 'location_id')
    op.add_column('encounter_diagnosis', sa.Column('condition_reference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('encounter_diagnosis', 'rank',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('encounter_diagnosis', 'use_display')
    op.drop_column('encounter_diagnosis', 'use_code')
    op.drop_column('encounter_diagnosis', 'use_system')
    op.drop_column('encounter_diagnosis', 'condition_display')
    op.drop_column('encounter_diagnosis', 'condition_id')
    op.drop_column('encounter_diagnosis', 'condition_type')
    op.add_column('encounter', sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.execute("CREATE TYPE encounterclass AS ENUM ('INPATIENT', 'AMBULATORY', 'OBSERVATION', 'EMERGENCY', 'VIRTUAL', 'HOME_HEALTH')")
    op.execute("ALTER TABLE encounter ALTER COLUMN class_code TYPE encounterclass USING NULL")
    op.execute("DROP TYPE IF EXISTS encounter_location_status")
    op.execute("CREATE TYPE encounterstatus AS ENUM ('PLANNED', 'IN_PROGRESS', 'ON_HOLD', 'DISCHARGED', 'COMPLETED', 'CANCELLED', 'DISCONTINUED', 'ENTERED_IN_ERROR', 'UNKNOWN')")
    op.execute("ALTER TABLE encounter ALTER COLUMN status TYPE encounterstatus USING NULL")
    op.execute("DROP TYPE IF EXISTS encounter_status")
    op.drop_column('encounter', 'part_of_id')
    op.drop_column('encounter', 'service_provider_display')
    op.drop_column('encounter', 'service_provider_id')
    op.drop_column('encounter', 'hosp_discharge_disposition_text')
    op.drop_column('encounter', 'hosp_discharge_disposition_display')
    op.drop_column('encounter', 'hosp_discharge_disposition_code')
    op.drop_column('encounter', 'hosp_discharge_disposition_system')
    op.drop_column('encounter', 'hosp_destination_display')
    op.drop_column('encounter', 'hosp_destination_id')
    op.drop_column('encounter', 'hosp_destination_type')
    op.drop_column('encounter', 'hosp_re_admission_text')
    op.drop_column('encounter', 'hosp_re_admission_display')
    op.drop_column('encounter', 'hosp_re_admission_code')
    op.drop_column('encounter', 'hosp_re_admission_system')
    op.drop_column('encounter', 'hosp_admit_source_text')
    op.drop_column('encounter', 'hosp_admit_source_display')
    op.drop_column('encounter', 'hosp_admit_source_code')
    op.drop_column('encounter', 'hosp_admit_source_system')
    op.drop_column('encounter', 'hosp_origin_display')
    op.drop_column('encounter', 'hosp_origin_id')
    op.drop_column('encounter', 'hosp_origin_type')
    op.drop_column('encounter', 'hosp_pre_admission_identifier_value')
    op.drop_column('encounter', 'hosp_pre_admission_identifier_system')
    op.drop_column('encounter', 'length_code')
    op.drop_column('encounter', 'length_system')
    op.drop_column('encounter', 'length_unit')
    op.drop_column('encounter', 'length_comparator')
    op.drop_column('encounter', 'length_value')
    op.drop_column('encounter', 'priority_text')
    op.drop_column('encounter', 'priority_display')
    op.drop_column('encounter', 'priority_code')
    op.drop_column('encounter', 'priority_system')
    op.drop_column('encounter', 'service_type_text')
    op.drop_column('encounter', 'service_type_display')
    op.drop_column('encounter', 'service_type_code')
    op.drop_column('encounter', 'service_type_system')
    op.drop_column('encounter', 'class_display')
    op.drop_column('encounter', 'class_version')
    op.drop_column('encounter', 'class_system')
    op.create_table('based_on',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_type', postgresql.ENUM('CARE_PLAN', 'DEVICE_REQUEST', 'MEDICATION_REQUEST', 'SERVICE_REQUEST', name='based_on_reference_type'), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], name=op.f('based_on_encounter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('based_on_pkey'))
    )
    op.create_index(op.f('ix_based_on_encounter_id'), 'based_on', ['encounter_id'], unique=False)
    op.drop_index(op.f('ix_encounter_participant_type_participant_id'), table_name='encounter_participant_type')
    op.drop_table('encounter_participant_type')
    op.drop_index(op.f('ix_encounter_status_history_encounter_id'), table_name='encounter_status_history')
    op.drop_table('encounter_status_history')
    op.drop_index(op.f('ix_encounter_reason_reference_encounter_id'), table_name='encounter_reason_reference')
    op.drop_table('encounter_reason_reference')
    op.drop_index(op.f('ix_encounter_identifier_encounter_id'), table_name='encounter_identifier')
    op.drop_table('encounter_identifier')
    op.drop_index(op.f('ix_encounter_hosp_special_courtesy_encounter_id'), table_name='encounter_hosp_special_courtesy')
    op.drop_table('encounter_hosp_special_courtesy')
    op.drop_index(op.f('ix_encounter_hosp_special_arrangement_encounter_id'), table_name='encounter_hosp_special_arrangement')
    op.drop_table('encounter_hosp_special_arrangement')
    op.drop_index(op.f('ix_encounter_hosp_diet_preference_encounter_id'), table_name='encounter_hosp_diet_preference')
    op.drop_table('encounter_hosp_diet_preference')
    op.drop_index(op.f('ix_encounter_episode_of_care_encounter_id'), table_name='encounter_episode_of_care')
    op.drop_table('encounter_episode_of_care')
    op.drop_index(op.f('ix_encounter_class_history_encounter_id'), table_name='encounter_class_history')
    op.drop_table('encounter_class_history')
    op.drop_index(op.f('ix_encounter_based_on_encounter_id'), table_name='encounter_based_on')
    op.drop_table('encounter_based_on')
    op.drop_index(op.f('ix_encounter_appointment_ref_encounter_id'), table_name='encounter_appointment_ref')
    op.drop_table('encounter_appointment_ref')
    op.drop_index(op.f('ix_encounter_account_encounter_id'), table_name='encounter_account')
    op.drop_table('encounter_account')
    # ### end Alembic commands ###
